# Generated by Django 4.2.30 on 2026-07-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_rating',
            field=models.CharField(choices=[('P', 'P - General (Mọi đối tượng)'), ('C13', 'C13 - 13+ (Từ 13 tuổi trở lên)'), ('C16', 'C16 - 16+ (Từ 16 tuổi trở lên)'), ('C18', 'C18 - 18+ (Từ 18 tuổi trở lên)')], default='P', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
