# Generated by Django 4.2.30 on 2026-07-03 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_age_rating_movie_cast_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='redeemed_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discount',
            name='allow_points_combination',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='applicable_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='applicable_movies',
            field=models.ManyToManyField(blank=True, related_name='applicable_discounts', to='cinema.movie'),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_golden_hour_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='min_tier',
            field=models.CharField(blank=True, choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Bronze', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.user')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='cinema.review')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewHelpfulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='cinema.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.user')),
            ],
            options={
                'unique_together': {('user', 'review')},
            },
        ),
    ]
