# Generated by Django 4.2.30 on 2026-07-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_booking_points_earned_booking_redeemed_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
