# Generated by Django 4.2.30 on 2026-07-30 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_seed_combos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.combo'),
        ),
    ]
